package ar.edu.unlam.pb2.enums;

public enum NivelEducativo {
	CELESTE, VERDE, AZUL, ROJA,
	PRIMER_GRADO,
	SEGUNDO_GRADO, TERCER_GRADO, CUARTO_GRADO, QUINTO_GRADO, SEXTO_GRADO,
	PRIMER_AÑO, SEGUNDO_AÑO, TERCER_AÑO, 
	CUARTO_AÑO, QUINTO_AÑO, SEXTO_AÑO
}
